version: "3.9"

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:16.0
    environment:
      - PGPORT=$DB_PORT
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ~/Documents/apps-db/${COMPOSE_PROJECT_NAME}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always

  back:
    container_name: ${COMPOSE_PROJECT_NAME}-back
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_PORT: $APP_PORT
        DB_HOST: $DB_HOST
        DB_PORT: $DB_PORT
        DB_TYPE: $DB_TYPE
        DB_NAME: $DB_NAME
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
    image: ${COMPOSE_PROJECT_NAME}-back
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
